<?php

defined('_JEXEC') or die;

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PayPal' => array($vendorDir . '/paypal/rest-api-sdk-php/lib'),
);
